version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

python:
  version: "3.7"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
