blank_issues_enabled: false
contact_links:
  - name: Cell2location Community Discussions
    url: https://github.com/BayraktarLab/cell2location/discussions
    about: Ask how to solve your problem using cell2location.
