blank_issues_enabled: false
contact_links:
  - name: scverse Discorse
    url: https://discourse.scverse.org/c/ecosytem/cell2location/
    about: Ask usage questions, how to solve your problems using cell2location and other scvi-tools packages.

  - name: cell2location Community Discussions [deprecated]
    url: https://discourse.scverse.org/c/ecosytem/cell2location/
    about: Find previous answers/issues. For new questions please use the link above.
