from .RegressionGeneBackgroundCoverageGeneTechnologyTorch import (
    RegressionGeneBackgroundCoverageGeneTechnologyTorch,
)
from .RegressionGeneBackgroundCoverageTorch import RegressionGeneBackgroundCoverageTorch

__all__ = ["RegressionGeneBackgroundCoverageTorch", "RegressionGeneBackgroundCoverageGeneTechnologyTorch"]
