from .RegressionGeneBackgroundCoverageTorch import RegressionGeneBackgroundCoverageTorch
from .RegressionGeneBackgroundCoverageGeneTechnologyTorch import RegressionGeneBackgroundCoverageGeneTechnologyTorch

__all__ = [
    "RegressionGeneBackgroundCoverageTorch",
    "RegressionGeneBackgroundCoverageGeneTechnologyTorch"
]