name: cellpymc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python = 3.7
  - pip
  - numpy >= 1.18.5
  - pandas >= 1.0.4
  - jupyter >= 1.0.0
  - leidenalg >= 0.8.0
  - python-igraph >= 0.8.2
  - nose >= 1.3.7
  - scanpy >= 1.5.1
  - scipy >= 1.4.1 
  - louvain >= 0.6.1
  - hyperopt >= 0.2.4
  - loompy >= 2.0.16
  - cmake >= 3.17.0
  - dill >= 0.3.1
  - ipython >= 7.15.0
  - bbknn >= 1.3.9
  - seaborn >= 0.10.1
  - matplotlib >= 3.2.1
  - request >= 2.83.1
  - mkl-service >= 2.3.0
  - pygpu >= 0.7.6
  - cython >= 0.29.17
  - pip:
    - plotnine==0.7.0
    - pymc3>=3.8
    - torch>=1.5.0
    - pyro-ppl>=1.3.1
    - sphinx
    - nbsphinx
    - sphinx_rtd_theme
